language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: RPe9UN97/X+rxYE6Icc2CkcCWTV3IsjeVzImsOX7s6rZEV2aVNNAG09TVaCs/zDvHqEG0bRrIaX5txzOCZ9TTWvHs9A39Btv/rvmptbd9Uk7bdjn+GjFm2nwOK95ViYE9QYMKnLyvRxCzcueY6yP0uMXVRYFuJC5iCG6/Bkc11Lpi5uH/ePqgDlEmXjoyIvv613ZDp7Qr2ilyNrzUjcREQg7bMFYX6GStfuCGz+QUsYqUssFSD2NA494EPWShQ7sbzNMzvIEwIwSnL8rv6m8Xz0kITZ9+GsU65U9XR0g0KuJ/C9aWaIoqyr/ZrWnCUS/8s0fqBqF3LROhpg0WHyHXnQGSFbEVRnukF+GJf1Mbcf/GOOJeoT1HciBIRrZJDCqbmMv6Nhp6ZeZDaDjFZ3EV5IaMEKP18pW5gbpxxH+UBtHOakE8T8nx/DvYhYVgKf4+xRX91fcGa7mSzYHr311HwX7pJhj7FnQMWEZe2GKbpnYS7ZqkQ6HqGaBvtMpnTpLBzaG/gOkFoaWFKdfOI5DgrDnPM2AVeNjyR3rincQHADPpoBzaKnJDNx+hcy9vN74iPnrp0YY5540sIw+ddSgvGbX/aJuTeKaDHQVjhUfi5F8vFAVmT8jjrIa5oNlQQbPP7ToSsGyZRUNTaHsPt9P20M/zQrPtclMLJDQ0nsdqIw=
  app: bbqtracker
  on:
    repo: morettisf/bbq-tracker
