var app = require('./public/js/app.js')
var nav = require('./public/js/nav.js')
var datepickr = require('./public/js/datepickr.js')
var moment = require('moment')
var sorttable = require('./public/js/sorttable.js')
var fetch = require('whatwg-fetch')
// var FormData = require('formdata-polyfill')