var logs = require('./public/js/logs.js')
var logHistory = require('./public/js/loghistory.js')
var accounts = require('./public/js/accounts.js')
var nav = require('./public/js/nav.js')
var datepickr = require('./public/js/datepickr.js')
var moment = require('moment')
var sorttable = require('./public/js/sorttable.js')
var fetch = require('whatwg-fetch')