module.exports = {

    device: [
      'Select device ---', 
      'Big Green Egg', 
      'Bradley - Electric', 
      'Broil King Keg', 
      'Broil King Smoke - Charcoal Horizontal', 
      'Cajun Injector - Electric',
      'Camp Chef - Propane',
      'Char-Broil - Electric',
      'Char-Broil - Charcoal Horizontal',
      'Char-Broil - Propane',
      'Char-Griller - Charcoal Horizontal',
      'Char-Griller - Charcoal Vertical',
      'Char-Griller - Pellet Horizontal',
      'Char-Griller Duo - Propane / Charcoal',
      'Cuisinart - Charcoal Vertical',
      'Cuisinart - Propane',
      'Dyna-Glo - Charcoal Vertical',
      'Dyna-Glo - Propane Vertical',
      'Grill - Propane',
      'Kamodo Big Joe - Charcoal',
      'Kamodo Joe Classic - Charcoal',
      'Kamodo Joe Jr. - Charcoal',
      'Kettle Grill - Charcoal', 
      'Kingsform - Charcoal Vertical',
      'King Kooker - Propane Vertical',
      "Lamberts Sweet Swine O'Mine Red Box - Charcoal",
      'Landmann USA Smoky Mountain - Charcoal Vertical',
      'Landmann USA Smoky Mountain - Electric Vertical',
      'Landmann USA Smoky Mountain - Propane',
      'Louisiana Grills - Charcoal Horizontal',
      'Lang - 36" Deluxe',      
      'Lang - 36" Original',
      'Lang - 36" Hybrid Patio',
      'Lang - 36" Hybrid Deluxe Patio',
      'Lang - 36" Hybrid Run-About BBQ Trailer',
      'Lang - 36" Hybrid Deluxe Run-About BBQ Trailer',
      'Lang - 36" Stretch Run-About',
      'Lang - 36" Stretch Deluxe Run-About',
      'Lang - 48" Deluxe',
      'Lang - 48" Deluxe Patio',
      'Lang - 48" Hybrid Deluxe Patio',
      'Lang - 48" Hybrid Patio',
      'Lang - 48" Original',
      'Lang - 48" Patio',
      'Lang - 60" Deluxe',
      'Lang - 60" Deluxe with Chargrill',
      'Lang - 60" Original',
      'Lang - 84" Deluxe',
      'Lang - 84" Deluxe with Chargrill',
      'Lang - 84" Deluxe Wide Body BBQ Wagon',
      'Lang - 84" Fat Boy',
      'Lang - 84" Fat Boy Deluxe',
      'Lang - 84" Fat Boy Kitchen',
      'Lang - 84" Fat Boy Kitchen Deluxe',
      'Lang - 84" Original',
      'Lang - 84" Tandem',
      'Lang - 84" Twin Deluxe',
      'Lang - 84" Twin Deluxe with Chargrill',
      'Lang - 108" Deluxe',
      'Lang - 108" Deluxe with Chargrill',
      'Lang - 108" Original',
      'Lang - 108" Kitchen',
      'Lang - 108" Kitchen Deluxe',
      'Lang - 108" Tandem',
      'Masterbuilt Bullet - Charcoal',
      'Masterbuilt - Electric Vertical',
      'Masterbuilt - Propane Vertical',
      'Meco - Charcoal Vertical',
      "Oklahoma Joe's - Charcoal Horizontal",
      "Oklahoma Joe's - Charcoal Vertical",
      "Oklahoma Joe's Longhorn - Propane / Charcoal",
      'Old Smokey - Electric',
      'Outsunny Backyard - Charcoal Horizontal',
      'Oven',
      'Pit Barrel Cooker',
      'Pit Boss - Charcoal Vertical',
      'Pit Boss - Pellet Horizontal',
      'Primo Kamado - Charcoal',
      'Primo Oval JR 200 - Charcoal',
      'Primo Oval LG 300 - Charcoal',
      'Primo Oval XL 400 - Charcoal',
      'REC TEC Mini Portable Wood Pellet Grill (RT-300)',
      'REC TEC Wood Pellet Grill (RT-680)',
      'Shirley Fabrication - Cabinet 24"x60" Modified Trailer',
      'Shirley Fabrication - Cabinet 24"x65" Modified Trailer',
      'Shirley Fabrication - Cabinet 24"x65" Trailer',
      'Shirley Fabrication - Cabinet 24"x65" Non-Insulated Trailer',
      'Shirley Fabrication - Cabinet 30"x96" Dual Axel Trailer',
      'Shirley Fabrication - Cabinet Patio 24"x42"',
      'Shirley Fabrication - Cabinet Patio 24"x50"',
      'Shirley Fabrication - Cabinet Patio 24"x60"',
      'Shirley Fabrication - Cabinet Patio 24"x65"',
      'Shirley Fabrication - Cabinet 24"x75" Straightback Trailer',
      'Shirley Fabrication - Doors Patio 24"x50"',
      'Shirley Fabrication - Trailer 24"x60"',
      'Shirley Fabrication - Trailer 24"x65"',
      'Smoke Hollow - Electric',
      'Smoke Hollow - Propane Vertical',
      'Southern Country - Charcoal Vertical',
      'Southern Country - Electric Vertical',
      'Traeger - Bronson 20"',
      'Traeger - Double Commercial Grill Trailer',
      'Traeger - Junior Elite 20"',
      'Traeger - Large Commercial Grill Trailer',
      'Traeger - Lil Pig',
      'Traeger - Lil Texas Elite 22"',
      'Traeger - Lone Star Elite',
      'Traeger - Pro Series 22"',
      'Traeger - Pro Series 34"',
      'Traeger - PTG + Grill',
      'Traeger - Renegade Elite',
      'Traeger - Select Elite',
      'Traeger - Select Pro',
      'Traeger - Tailgater',
      'Traeger - Texas Elite 34"',
      'Traeger - XL',
      'Triprel Patio Smoker Grill - Charcoal',
      'Ugly Drum Smoker',
      'Weber Kettle Grill',
      'Weber Smokey Mountain - Charcoal Vertical',
      'Other'
    ],

    meat: [
      'Select meat ---', 
      'Bacon',
      'Beef Brisket',
      'Beef Chuck Roast',
      'Beef Rib Roast', 
      'Beef Ribs', 
      'Beef Rib Tips',
      'Beef Roast',
      'Beef Tri-tip',
      'Chicken (whole)',
      'Chicken Breast',
      'Chicken Drumsticks',
      'Chicken Legs',
      'Chicken Thighs',
      'Duck',
      'Fish',
      'Ham',
      'Hamburger',
      'Hot Dogs',
      'Lamb',
      'Pig (whole)',
      'Pizza',
      'Pork Belly',
      'Pork Ribs (baby backs)', 
      'Pork Ribs (spares)', 
      'Pork Rib Tips', 
      'Pork Roast',
      'Pork Shoulder',
      'Pork Loin',
      'Pork Tenderloin',
      'Sausage',
      'Steak',
      'Turkey (whole)',
      'Turkey Breast',
      'Turkey Drumsticks',
      'Turkey Legs',
      'Turkey Thighs',
      'Other'
    ],

    fuel: [
      'Select fuel ---', 
      'Briquettes', 
      'Lump Charcoal', 
      'Pellets', 
      'Propane',
      'Wood'
    ],

    wood: [
      'Select wood ---', 
      'Acacia', 
      'Alder', 
      'Almond', 
      'Apple', 
      'Apricot', 
      'Ash', 
      'Bay', 
      'Birch', 
      'Blackberry', 
      'Butternut', 
      'Cherry', 
      'Chestnut', 
      'Crabapple', 
      'Fig', 
      'Grapefruit', 
      'Grapevines', 
      'Hickory', 
      'Kiawe', 
      'Lemon', 
      'Lilac', 
      'Maple',
      'Mesquite', 
      'Mulberry', 
      'Nectarine', 
      'Oak', 
      'Olive', 
      'Orange', 
      'Peach', 
      'Pear', 
      'Pecan', 
      'Peppercorn', 
      'Persimmon', 
      'Pimento', 
      'Plum', 
      'Sassafras', 
      'Seaweed', 
      'None', 
      'Other'
    ]

}






