module.exports = {

    device: [
      'Select device ---', 
      'Big Green Egg', 
      'Bradley - Electric', 
      'Broil King Keg', 
      'Broil King Smoke - Charcoal Horizontal', 
      'Cajun Injector - Electric',
      'Camp Chef - Propane',
      'Char-Broil - Electric',
      'Char-Broil - Charcoal Horizontal',
      'Char-Broil - Propane',
      'Char-Griller - Charcoal Horizontal',
      'Char-Griller - Charcoal Vertical',
      'Char-Griller - Pellet Horizontal',
      'Char-Griller Duo - Propane / Charcoal',
      'Cuisinart - Charcoal Vertical',
      'Cuisinart - Propane',
      'Dyna-Glo - Charcoal Vertical',
      'Dyna-Glo - Propane Vertical',
      'Grill - Propane',
      'Kamodo Big Joe - Charcoal',
      'Kamodo Joe Classic - Charcoal',
      'Kamodo Joe Jr. - Charcoal',
      'Kettle Grill - Charcoal', 
      'Kingsform - Charcoal Vertical',
      'King Kooker - Propane Vertical',
      "Lamberts Sweet Swine O'Mine Red Box - Charcoal",
      'Landmann USA Smoky Mountain - Charcoal Vertical',
      'Landmann USA Smoky Mountain - Electric Vertical',
      'Landmann USA Smoky Mountain - Propane',
      'Louisiana Grills - Charcoal Horizontal',
      'Masterbuilt Bullet - Charcoal',
      'Masterbuilt - Electric Vertical',
      'Masterbuilt - Propane Vertical',
      'Meco - Charcoal Vertical',
      "Oklahoma Joe's - Charcoal Horizontal",
      "Oklahoma Joe's - Charcoal Vertical",
      "Oklahoma Joe's Longhorn - Propane / Charcoal",
      'Old Smokey - Electric',
      'Outsunny Backyard - Charcoal Horizontal',
      'Oven',
      'Oil Drum',
      'Pit Boss - Charcoal Vertical',
      'Pit Boss - Pellet Horizontal',
      'Primo Kamado - Charcoal',
      'Primo Oval JR 200 - Charcoal',
      'Primo Oval LG 300 - Charcoal',
      'Primo Oval XL 400 - Charcoal',
      'Smoke Hollow - Electric',
      'Smoke Hollow - Propane Vertical',
      'Southern Country - Charcoal Vertical',
      'Southern Country - Electric Vertical',
      'Triprel Patio Smoker Grill - Charcoal',
      'Weber Kettle Grill',
      'Weber Smokey Mountain - Charcoal Vertical',
      'Other'
    ],

    meat: [
      'Select meat ---', 
      'Beef Brisket',
      'Beef Rib Roast', 
      'Beef Ribs', 
      'Beef Rib Tips',
      'Beef Tri-tip',
      'Chicken (whole)',
      'Chicken Breast',
      'Chicken Drumsticks',
      'Chicken Legs',
      'Chicken Thighs',
      'Fish',
      'Ham',
      'Hamburger',
      'Hot Dogs',
      'Lamb',
      'Pig (whole)',
      'Pizza',
      'Pork Ribs (baby backs)', 
      'Pork Ribs (spares)', 
      'Pork Rib Tips', 
      'Pork Shoulder',
      'Sausage',
      'Steak',
      'Turkey (whole)',
      'Turkey Breast',
      'Turkey Drumsticks',
      'Turkey Legs',
      'Turkey Thighs',
      'Other'
    ],

    fuel: [
      'Select fuel ---', 
      'Briquettes', 
      'Lump Charcoal', 
      'Pellets', 
      'Propane',
      'Wood'
    ],

    wood: [
      'Select wood ---', 
      'Acacia', 
      'Alder', 
      'Almond', 
      'Apple', 
      'Apricot', 
      'Ash', 
      'Bay', 
      'Birch', 
      'Blackberry', 
      'Butternut', 
      'Cherry', 
      'Chestnut', 
      'Crabapple', 
      'Fig', 
      'Grapefruit', 
      'Grapevines', 
      'Hickory', 
      'Kiawe', 
      'Lemon', 
      'Lilac', 
      'Maple',
      'Mesquite', 
      'Mulberry', 
      'Nectarine', 
      'Oak', 
      'Olive', 
      'Orange', 
      'Peach', 
      'Pear', 
      'Pecan', 
      'Peppercorn', 
      'Persimmon', 
      'Pimento', 
      'Plum', 
      'Sassafras', 
      'Seaweed', 
      'None', 
      'Other'
    ]

}






